<?php

/**
 * @file
 * Hooks and constants for islandora_form_fieldpanel.
 */

/**
 * Constants
 */
define('ISLANDORA_FORM_FIELDPANEL_THEME_FIELDPANEL', 'fieldpanel');
define('ISLANDORA_FORM_FIELDPANEL_THEME_FIELDPANE', 'fieldpane');
define('ISLANDORA_FORM_FIELDPANEL_PATH_MODULE', drupal_get_path('module', 'islandora_form_fieldpanel') . '/');
define('ISLANDORA_FORM_FIELDPANEL_PATH_INCLUDES', ISLANDORA_FORM_FIELDPANEL_PATH_MODULE . 'includes/');
define('ISLANDORA_FORM_FIELDPANEL_PATH_THEME', ISLANDORA_FORM_FIELDPANEL_PATH_MODULE . 'theme/');
define('ISLANDORA_FORM_FIELDPANEL_PATH_JS', ISLANDORA_FORM_FIELDPANEL_PATH_MODULE . 'js/');
define('ISLANDORA_FORM_FIELDPANEL_PATH_CSS', ISLANDORA_FORM_FIELDPANEL_PATH_MODULE . 'css/');

/**
 * Implements hook_element_info().
 */
function islandora_form_fieldpanel_element_info() {
  return array(
    'fieldpanel' => array(
      '#input' => TRUE,
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#process' => array('islandora_form_fieldpanel_fieldpanel_process'),
      '#theme_wrappers' => array('fieldpanel', 'form_element'),
    ),
    'fieldpane' => array(
      '#input' => TRUE,
      '#process' => array('islandora_form_fieldpanel_fieldpane_process'),
      '#user_data' => array('add' => TRUE, 'delete' => TRUE),
      '#theme_wrappers' => array('fieldpane'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_form_fieldpanel_theme($existing, $type, $theme, $path) {
  return array(
    // Single Field Panel holds multiple field panes.
    ISLANDORA_FORM_FIELDPANEL_THEME_FIELDPANEL => array(
      'render element' => 'element',
      'template' => 'templates/FieldPanel',
      'file' => 'includes/FieldPanel.inc',
    ),
    // The content of a single fieldpane.
    ISLANDORA_FORM_FIELDPANEL_THEME_FIELDPANE => array(
      'render element' => 'element',
      'file' => 'includes/FieldPane.inc',
    ),
  );
}

/**
 * Process the 'fieldpane' Element.
 *
 * @param array $element
 *   The element to be processed.
 * @param mixed $edit
 *   The submitted value for this element, or NULL.
 * @param array $form_state
 *   The drupal form state.
 * @param array $complete_form
 *   The drupal form.
 *
 * @return array
 *   The processed element.
 */
function islandora_form_fieldpanel_fieldpane_process(array $element, array &$form_state, array $complete_form = NULL) {
  form_load_include($form_state, 'inc', 'islandora_form_fieldpanel', 'includes/FieldPane');
  return FieldPane::Process($element, $form_state, $complete_form);
}

/**
 * Process the 'fieldpanel' Element.
 *
 * @param array $element
 *   The element to be processed.
 * @param mixed $edit
 *   The submitted value for this element, or NULL.
 * @param array $form_state
 *   The drupal form state.
 * @param array $complete_form
 *   The drupal form.
 *
 * @return array
 *   The processed element.
 */
function islandora_form_fieldpanel_fieldpanel_process(array $element, array &$form_state, array $complete_form = NULL) {
  form_load_include($form_state, 'inc', 'islandora_form_fieldpanel', 'includes/FieldPanel');
  return FieldPanel::Process($element, $form_state, $complete_form);
}

function islandora_form_fieldpanel_form_element_fieldpanel_ajax_alter(FormElement $element, array &$form, array &$form_state) {
  $triggering_element = $form_state['triggering_element'];
  $action = $triggering_element['#ajax']['params']['action'];
  switch ($action) {
    case 'add':
      islandora_form_fieldpanel_form_element_fieldpane_ajax_add($element, $form, $form_state);
      break;
    case 'delete':
      islandora_form_fieldpanel_form_element_fieldpane_ajax_delete($element, $form, $form_state);
      break;
  }
}

function islandora_form_fieldpanel_form_element_fieldpane_ajax_add(FormElement $element, array &$form, array &$form_state) {
  dpm($element);
  dpm($form_state['triggering_element']);
//  $pane = $element->findElement($form_state['triggering_element']['#ajax']['params']['child']);
//  $new_pane = clone $pane;
//  $new_pane->eachDecendant(function($element) { $element->default_value = NULL; });
//  $element->adopt($new_pane);
//  $form[] = $new_pane->toArray();
}

function islandora_form_fieldpanel_form_element_fieldpane_ajax_delete(FormElement $element, array &$form, array &$form_state) {
  $pane = $element->findElement($form_state['triggering_element']['#ajax']['params']['child']);
  $pane->orphan();
  foreach (element_children($form) as $child) {
    if ($form[$child]['#hash'] == $pane->hash) {
      unset($form[$child]);
      break;
    }
  }
}
